const data = [
    {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },
    {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },  {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },  {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },  {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },  {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },  {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },  {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },  {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },  {
        country: "",
        director : "",
        duration : "",
        year : "",
        description : "",
        image : "",
        trailer : "",
        nameRU : "",
        nameEN : "",
        thumbnail : "",
        movieId : "",
        trailerLink : "",
    },
];

module.exports = data;